### ISSUE TITLE
laravelの新しいプロジェクトをcomposer installしてきてhello worldできるところまで行う

### ISSUE THREAD

**Issue by kei1111** [soichirohaga/musicsenpai#4]
## やること
- laravelインストール　バージョンは7以前の方が好ましいです
- hello worldと表示できればこのissuesでは完了となります

**Comment by soichirohaga** [comment]
![スクリーンショット 2020-12-08 18 43 42](https://user-images.githubusercontent.com/74962690/101467242-6867d180-3985-11eb-8587-1e024d934623.png)
